// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHAnalytics.Infrastructure.Data;

#nullable disable

namespace SHAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240901033420_Add_BattleArea_Table")]
    partial class Add_BattleArea_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SHAnalytics.Core.Entities.BattleArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("BattleAreas");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.InGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("GameVersion")
                        .HasColumnType("REAL");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("InGames");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeathCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedHero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InGameId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.BattleArea", b =>
                {
                    b.HasOne("SHAnalytics.Core.Entities.Session", "Session")
                        .WithMany("BattleAreas")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.InGame", b =>
                {
                    b.HasOne("SHAnalytics.Core.Entities.Player", "Player")
                        .WithMany("InGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.Session", b =>
                {
                    b.HasOne("SHAnalytics.Core.Entities.InGame", "InGame")
                        .WithMany("Sessions")
                        .HasForeignKey("InGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InGame");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.InGame", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.Player", b =>
                {
                    b.Navigation("InGames");
                });

            modelBuilder.Entity("SHAnalytics.Core.Entities.Session", b =>
                {
                    b.Navigation("BattleAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
